//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EntityFramework.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        internal static string addButonu {
            get {
                return ResourceManager.GetString("addButonu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakiye.
        /// </summary>
        internal static string addlblBalance {
            get {
                return ResourceManager.GetString("addlblBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart Numarası.
        /// </summary>
        internal static string addlblCartId {
            get {
                return ResourceManager.GetString("addlblCartId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart Tipi.
        /// </summary>
        internal static string addlblCartType {
            get {
                return ResourceManager.GetString("addlblCartType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsim.
        /// </summary>
        internal static string addlblFirstName {
            get {
                return ResourceManager.GetString("addlblFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yemek Ücreti.
        /// </summary>
        internal static string addlblFoodPrice {
            get {
                return ResourceManager.GetString("addlblFoodPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soy İsim.
        /// </summary>
        internal static string addlblLastName {
            get {
                return ResourceManager.GetString("addlblLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağlan.
        /// </summary>
        internal static string bağlan {
            get {
                return ResourceManager.GetString("bağlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağlantı Durumu.
        /// </summary>
        internal static string baglantiDurumu {
            get {
                return ResourceManager.GetString("baglantiDurumu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçiş İzni Ver.
        /// </summary>
        internal static string btnBYPASS {
            get {
                return ResourceManager.GetString("btnBYPASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        internal static string btnRemove {
            get {
                return ResourceManager.GetString("btnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart Numarası Ara.
        /// </summary>
        internal static string CartIdAl {
            get {
                return ResourceManager.GetString("CartIdAl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakiye.
        /// </summary>
        internal static string dgwBakiye {
            get {
                return ResourceManager.GetString("dgwBakiye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gün.
        /// </summary>
        internal static string dgwGun {
            get {
                return ResourceManager.GetString("dgwGun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string dgwId {
            get {
                return ResourceManager.GetString("dgwId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsim.
        /// </summary>
        internal static string dgwIsim {
            get {
                return ResourceManager.GetString("dgwIsim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart Numarası.
        /// </summary>
        internal static string dgwKartNumarası {
            get {
                return ResourceManager.GetString("dgwKartNumarası", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart Tipi.
        /// </summary>
        internal static string dgwKartTipi {
            get {
                return ResourceManager.GetString("dgwKartTipi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alo.
        /// </summary>
        internal static string dgwproducts1 {
            get {
                return ResourceManager.GetString("dgwproducts1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soy İsim.
        /// </summary>
        internal static string dgwSoyisim {
            get {
                return ResourceManager.GetString("dgwSoyisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yemek Ücreti.
        /// </summary>
        internal static string dgwYemekUcreti {
            get {
                return ResourceManager.GetString("dgwYemekUcreti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Ekle.
        /// </summary>
        internal static string groupBoxIsmi {
            get {
                return ResourceManager.GetString("groupBoxIsmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Güncelle.
        /// </summary>
        internal static string groupBoxUpdateIsmi {
            get {
                return ResourceManager.GetString("groupBoxUpdateIsmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        internal static string guncelleButonu {
            get {
                return ResourceManager.GetString("guncelleButonu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsim Ara.
        /// </summary>
        internal static string isimAra {
            get {
                return ResourceManager.GetString("isimAra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapat.
        /// </summary>
        internal static string kapat {
            get {
                return ResourceManager.GetString("kapat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Düzenle.
        /// </summary>
        internal static string KullanıcıDüzenle {
            get {
                return ResourceManager.GetString("KullanıcıDüzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Ekle.
        /// </summary>
        internal static string KullanıcıEkle {
            get {
                return ResourceManager.GetString("KullanıcıEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Sil.
        /// </summary>
        internal static string KullanıcıSil {
            get {
                return ResourceManager.GetString("KullanıcıSil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Sistemi.
        /// </summary>
        internal static string KullanıcıSistemi {
            get {
                return ResourceManager.GetString("KullanıcıSistemi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakiye 50&apos;den büyük olmalıdır..
        /// </summary>
        internal static string lblaciklama1 {
            get {
                return ResourceManager.GetString("lblaciklama1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yemek Ücreti 15&apos;ten küçük olmalıdır..
        /// </summary>
        internal static string lblaciklama2 {
            get {
                return ResourceManager.GetString("lblaciklama2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncellemek istediğiniz kullanıcının satırına tıklayıp bilgilerini güncelleme ekranına çekiniz.
        /// </summary>
        internal static string lblaciklama3 {
            get {
                return ResourceManager.GetString("lblaciklama3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silmek istediğiniz kullanıcının satırını seçip &apos;Sil&apos; butonuna basmalısınız.(Satırı seçmeden &apos;Sil&apos; butonuna basmayınız!!).
        /// </summary>
        internal static string lblaciklama4 {
            get {
                return ResourceManager.GetString("lblaciklama4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil Seçimi.
        /// </summary>
        internal static string menu {
            get {
                return ResourceManager.GetString("menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string port {
            get {
                return ResourceManager.GetString("port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakiye Sıfırla(Memur).
        /// </summary>
        internal static string TopluİslembtnBakiyeSifirlaMemur {
            get {
                return ResourceManager.GetString("TopluİslembtnBakiyeSifirlaMemur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        internal static string TopluİslembtnKaydet {
            get {
                return ResourceManager.GetString("TopluİslembtnKaydet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıtları Sil.
        /// </summary>
        internal static string TopluİslembtnKayitlariSil {
            get {
                return ResourceManager.GetString("TopluİslembtnKayitlariSil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Kayıtlarını Silme İşlemi  =&gt;.
        /// </summary>
        internal static string TopluİslemlblLogKaydıSilme {
            get {
                return ResourceManager.GetString("TopluİslemlblLogKaydıSilme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memur Bakiyesini Sıfırla(0)  =.
        /// </summary>
        internal static string TopluİslemlblMemurBakiyeSifirla {
            get {
                return ResourceManager.GetString("TopluİslemlblMemurBakiyeSifirla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misafir Ücreti =.
        /// </summary>
        internal static string TopluİslemlblMisafirUcreti {
            get {
                return ResourceManager.GetString("TopluİslemlblMisafirUcreti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yemek Ücreti(Memur) =.
        /// </summary>
        internal static string TopluİslemlblYemekUcretiMemur {
            get {
                return ResourceManager.GetString("TopluİslemlblYemekUcretiMemur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yemek Ücreti(Müdür) =.
        /// </summary>
        internal static string TopluİslemlblYemekUcretiMudur {
            get {
                return ResourceManager.GetString("TopluİslemlblYemekUcretiMudur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turnike.
        /// </summary>
        internal static string Turnike {
            get {
                return ResourceManager.GetString("Turnike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçiniz...
        /// </summary>
        internal static string updateChoose {
            get {
                return ResourceManager.GetString("updateChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yemekhane Otomasyonu.
        /// </summary>
        internal static string YemekhaneOtomasyonu {
            get {
                return ResourceManager.GetString("YemekhaneOtomasyonu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplu İşlemler.
        /// </summary>
        internal static string YemekhaneYöneticiTopluİslemlerButon {
            get {
                return ResourceManager.GetString("YemekhaneYöneticiTopluİslemlerButon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yenile.
        /// </summary>
        internal static string yenile {
            get {
                return ResourceManager.GetString("yenile", resourceCulture);
            }
        }
    }
}
